services:
  app:
    container_name: mugiwaras-app
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
  
    command: bash -c "python build_knowledge_graph.py && uvicorn packages.api.app.main:app --host 0.0.0.0 --port 8000 --reload"